// <auto-generated />
using System;
using DesignPatternsDay.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesignPatternsDay.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DesignPatternsDay.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOrganic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Vegetables",
                            CreatedAt = new DateTime(2026, 5, 22, 17, 15, 8, 379, DateTimeKind.Local).AddTicks(211),
                            IsOrganic = true,
                            Name = "Organic Cabbage",
                            Price = 50m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Category = "Meats",
                            CreatedAt = new DateTime(2026, 5, 22, 17, 15, 8, 379, DateTimeKind.Local).AddTicks(225),
                            IsOrganic = false,
                            Name = "Beef Steak",
                            Price = 150m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            Category = "Beverages",
                            CreatedAt = new DateTime(2026, 5, 22, 17, 15, 8, 379, DateTimeKind.Local).AddTicks(227),
                            IsOrganic = true,
                            Name = "Mango Juice",
                            Price = 25m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 4,
                            Category = "Vegetables",
                            CreatedAt = new DateTime(2026, 5, 22, 17, 15, 8, 379, DateTimeKind.Local).AddTicks(228),
                            IsOrganic = true,
                            Name = "Broccoli",
                            Price = 35m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 5,
                            Category = "Fruits",
                            CreatedAt = new DateTime(2026, 5, 22, 17, 15, 8, 379, DateTimeKind.Local).AddTicks(228),
                            IsOrganic = false,
                            Name = "Strawberries",
                            Price = 45m,
                            Stock = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
